services:
  - type: web
    name: virtual-finance-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn virtual_finance.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: virtual_finance
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
    autoDeploy: true
    preDeployCommand: |
          python manage.py migrate
          python manage.py create_admin

