

services:
  - type: web
    name: virtual-finance-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn virtual_finance.wsgi:application --bind 0.0.0.0:$PORT
    pythonVersion: 3.10

    envVars:
      - Key: DATABASE_URL
        Value: postgresql://virtual_finance_user:mINhlmZC84IFFjcJxn3khPp8TVvELQ89@dpg-d031elqdbo4c73c6kf00-a.oregon-postgres.render.com/virtual_finance

        fromDatabase:
          name: virtual_finance
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False

    preDeployCommand: |
      python manage.py migrate
      python manage.py create_admin
      python manage.py collectstatic --noinput
