# Generated by Django 5.2 on 2025-04-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ledgeraccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='chart_of_accounts_type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='default', max_length=10),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountgroup'),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.RemoveField(
            model_name='ledgeraccount',
            name='created_at',
        ),
    ]
