# Generated by Django 5.2 on 2025-04-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_ledgeraccount_unique_together_and_more'),
        ('user_mgmt', '0006_company_chart_of_accounts_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='user_mgmt.company'),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='accounting.accountgroup'),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
