# Generated by Django 5.2 on 2025-04-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_ledgeraccount_company_and_more'),
    ]

    operations = [
    ]
