# Generated by Django 5.1.7 on 2025-04-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20250409_1641'),
        ('user_mgmt', '0006_company_chart_of_accounts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to='user_mgmt.company'),
        ),
    ]
