# Generated by Django 5.1.7 on 2025-04-15 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_ledgeraccount_created_at_and_more'),
        ('user_mgmt', '0006_company_chart_of_accounts_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountgroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroups', to='accounting.accountgroup'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.company'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='nature',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='chart_of_accounts_type',
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accountgroup',
            name='is_active',
        ),
    ]
