# Generated by Django 5.2 on 2025-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_accountgroup_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
