# Generated by Django 5.2 on 2025-05-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_ledgeraccount_balance'),
        ('user_mgmt', '0006_company_chart_of_accounts_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='main_party_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Both')], default='customer', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='ledgeraccount',
            unique_together={('name', 'company')},
        ),
    ]
