# Generated by Django 5.2 on 2025-05-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_ledgeraccount_is_customer_ledgeraccount_is_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='main_party_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('dual', 'Dual')], default='customer', max_length=20),
        ),
    ]
