# Generated by Django 5.1.7 on 2025-04-10 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_alter_accountgroup_company'),
        ('user_mgmt', '0006_company_chart_of_accounts_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_customer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment'), ('JOURNAL', 'Journal'), ('CONTRA', 'Contra')], max_length=10)),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('gst_type', models.CharField(choices=[('CGST', 'CGST'), ('SGST', 'SGST'), ('IGST', 'IGST'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.party')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_debit', models.BooleanField()),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ledgeraccount')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vouchers.voucher')),
            ],
        ),
    ]
