# Generated by Django 5.2 on 2025-04-16 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_ledgeraccount_balance'),
        ('user_mgmt', '0006_company_chart_of_accounts_type'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='party',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='invoice_number',
            new_name='reference_number',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='gst_rate',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='gst_type',
        ),
        migrations.RemoveField(
            model_name='voucheritem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='voucheritem',
            name='is_debit',
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Receipt', 'Receipt'), ('Payment', 'Payment'), ('Estimation', 'Estimation'), ('PurchaseOrder', 'Purchase Order'), ('Expense', 'Expense'), ('Income', 'Income'), ('Journal', 'Journal Entry')], max_length=50),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.company')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ledgeraccount')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.voucher')),
            ],
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
