# Generated by Django 5.2 on 2025-05-15 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_rename_credit_journalentry_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='against_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='vouchers.voucher'),
        ),
    ]
