# Generated by Django 5.2 on 2025-05-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_alter_voucher_voucher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('RECEIPT', 'Receipt from Customer'), ('PAYMENT', 'Payment to Supplier'), ('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('ESTIMATION', 'Estimation'), ('PURCHASE_ORDER', 'Purchase Order'), ('CONTRA', 'Contra'), ('JOURNAL', 'Journal Entry'), ('DEBIT_NOTE', 'Debit Note'), ('CREDIT_NOTE', 'Credit Note')], max_length=20),
        ),
    ]
