# Generated by Django 5.2 on 2025-05-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_alter_voucher_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheritem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
