# Generated by Django 5.2 on 2025-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_voucheritem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheritem',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
