# Generated by Django 5.2 on 2025-06-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_voucheritem_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
