# Generated by Django 5.1.7 on 2025-04-05 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_alter_company_address_alter_company_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
