# Generated by Django 5.1.7 on 2025-04-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0003_company_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(default='N/A'),
        ),
    ]
