# Generated by Django 5.2 on 2025-04-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0005_alter_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='chart_of_accounts_type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='default', max_length=10),
        ),
    ]
