# Generated by Django 5.2 on 2025-05-26 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0007_company_account_name_company_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
