# Generated by Django 5.2 on 2025-05-27 07:47

import user_mgmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0009_company_logo_company_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=user_mgmt.models.logo_upload_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=user_mgmt.models.qr_upload_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=user_mgmt.models.signature_upload_path),
        ),
    ]
